name: nlp
description: A Flutter payment wallet application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.3.0
  
  # Animations & Effects
  animations: ^2.0.11
  shimmer: ^3.0.0
  
  # Charts & Graphs
  fl_chart: ^0.69.2
  
  # Credit Card UI
  flutter_credit_card: ^4.1.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  
  # SVG Support
  flutter_svg: ^2.2.0
  
  # State Management
  provider: ^6.1.5
  
  # Internationalization
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/
  #   - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
